logo: # add logo name
title: Pemilu FMIPA 2017
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "humam121.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: PEMILU FMIPA 2017 # add banner title
banner-desc: Pemilihan Umum Ketua Angkatan FMIPA ITB Angkatan 2017 # add banner description

# Author settings
author-pic: # your photo
author-name: # your name
about-author: # about author
email: humam121@gmail.com # your email
phone: 0896-7913-5173 # your pnone number
website: LINE: humamsan # you website

# Social link
instagram_url: https://www.instagram.com/fmipaitb17/ # add url link

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
